Import('env')

data = """
	objects.boson
	fragment1.3ds
"""

destinationdir = env['KDEDATA'] + '/boson/themes/species/neutral/objects'

env.Install(destinationdir, env.make_list(data))
env.Alias('install', destinationdir)
