// This file was generated from bogl_1_2_1_decl_p.boglc
// Do not edit this file (all changes will be lost)!

#ifndef BOGL_1_2_1_DECL_P_H
#define BOGL_1_2_1_DECL_P_H

#ifndef BOGL_H
#error Never include this file directly! Include bogl.h instead!
#endif

#include "bogl/bogl_do_dlopen.h"


#include "bogl_1_2_decl_p.h"



#include "extensions/arb_multitexture_decl_p.h"


#endif // BOGL_1_2_1_DECL_P_H
