#!/bin/bash

if [ -z "$1" ]; then
	echo "You must pass a source directory as first parameter to this script"
	exit 1
fi
if [ -z "$2" ]; then
	echo "You must pass a destination directory as second parameter to this script"
	exit 1
fi

SRC=$1
DST=$2

copy_extensions="cpp hpp h xbm"
#copy_data_extensions="tga" #AB: I am not 100% sure if these files are GPL

SRC=`echo $SRC | sed "s,/$,,"`
DST=`echo $DST | sed "s,/$,,"`
files_find=""
files_find_not=""
copy_files_find_params=""
copy_files_find_not_params=""
foo1=""
for i in $copy_extensions; do
	files="$files `find -type f `"
	if [ ! -z "$copy_file_find_params" ]; then
		copy_file_find_params="$copy_file_find_params -o"
	fi

	# AB: this does not work when a file named "*.$i" is in the current
	# directory. i have no idea how to escape " correctly to fix that.
	# therefore we use -regex instead
#	copy_file_find_params="$copy_file_find_params -name *.$i"

	copy_file_find_params="$copy_file_find_params -regex .+\.$i"
	copy_file_find_not_params="$copy_file_find_not_params ! -regex .+\.$i"
done
copy_file_find_not_params="$copy_file_find_not_params ! -name Makefile"
copy_file_find_not_params="$copy_file_find_not_params ! -name Makefile.in"
copy_file_find_not_params="$copy_file_find_not_params ! -name Makefile.am"
copy_file_find_not_params="$copy_file_find_not_params ! -name Root"
copy_file_find_not_params="$copy_file_find_not_params ! -name Repository"
copy_file_find_not_params="$copy_file_find_not_params ! -name Entries"
copy_file_find_not_params="$copy_file_find_not_params ! -name ufo_config_gnu.hpp.in"
copy_file_find_not_params="$copy_file_find_not_params ! -name configure.in.in"
copy_file_find_not_params="$copy_file_find_not_params ! -regex .*\.svn/.*"

if [ -e $DST ]; then
	echo "\"$DST\" already exists - we will delete files in it. Continue? (y/n)"
	read answer
	if [ "x$answer" != "xy" ]; then
		echo "exiting"
		exit 0
	fi



	echo "Doing make clean in $DST"
	make -C $DST clean 2>/dev/null >/dev/null

	files=`find $DST -type f $copy_file_find_not_params`
	if [ ! -z "$files" ]; then
		echo "There are some unknown files in $DST. Please delete them first"
		echo "$files"
		exit 1
	fi

	files=`find $DST $copy_file_find_params`

	# TODO: remove from cvs
	if [ ! -z "$files" ]; then
		echo "Deleting old files in $DST"
		rm $files
	fi
fi

echo "Copying from $SRC to $DST"
mkdir -p $DST
mkdir -p $DST/include
mkdir -p $DST/src

src_files=`find $SRC/src -type f $copy_file_find_params | sort`
include_files=`find $SRC/include -type f $copy_file_find_params`
for i in $src_files $include_files; do
	dir=`dirname $i | sed "s,$SRC,,"`
	file=`basename $i`

	mkdir -p "$DST$dir"
	cp "$i" "$DST$dir/$file"
done

# TODO: data

make_makefile_am() {
	makefile=$1
	src_files=$2
	all_dirs=$3
	lib=`dirname $makefile | sed "s,.*/,,"`

	if [ -z "$lib" ]; then
		echo "Oops NULL libname"
		exit 1
	fi
	if [ "$lib" = "src" ]; then
		lib="ufo"
	fi

	files=
	current_dir=`dirname $makefile`
	for i in $src_files; do
		dir="$DST/`dirname $i | sed "s,$SRC/,,"`"
		if [ "$dir" = "$current_dir" ]; then
			file=`basename $i`
			files="$files $file"
		fi
	done

	if [ -z "$files" ]; then
		echo "Oops no files found"
		exit 1
	fi

	echo "# autogenerated Makefile.am" > $makefile
	echo "# all changes will be lost when the next ufo version is imported" >> $makefile
	echo "" >> $makefile
	echo -n "SUBDIRS =" >> $makefile
	for i in $all_dirs; do
		if [ -z "`echo $DST/$i | sed "s,^$current_dir/.*,,"`" ]; then
			dir=`echo $DST/$i | sed "s,$current_dir/,,"`
			if [ ! -z "$dir" -a ! -z "`echo $dir | sed "s,.*/.*,,"`" ]; then
				echo -n " $dir" >> $makefile
			fi
		fi
	done
	echo " ." >> $makefile
	echo "" >> $makefile
	echo "INCLUDES = -I\$(top_srcdir)/`basename $DST`/include -I\$(top_srcdir)/bogl \$(all_includes)" >> $makefile
	echo "" >> $makefile
	echo "noinst_LTLIBRARIES = lib$lib.la" >> $makefile
	echo "" >> $makefile
	echo -n "lib${lib}_la_SOURCES =" >> $makefile
	for file in $files; do
		echo " \\" >> $makefile
		echo -n "	$file" >> $makefile
	done
	echo "" >> $makefile
	echo "" >> $makefile
}

echo "Generating Makefile.am files"

all_dirs=
prev_dir=
for i in $src_files; do
	dir=`dirname $i | sed "s,$SRC/,,"`
	if [ "x$dir" != "x$prev_dir" ]; then
		all_dirs="$all_dirs $dir"
		prev_dir=$dir
	fi
done

all_dirs=`echo $all_dirs | sort | uniq`

for i in $all_dirs; do
	make_makefile_am "$DST/$i/Makefile.am" "$src_files" "$all_dirs"
done

# src/Makefile.am needs additional modification
echo -n "libufo_la_LIBADD =" >> $DST/src/Makefile.am
for i in $all_dirs; do
	if [ "$i" != "src" ]; then
		lib=`echo $i | sed "s,.*/,,"`
		echo " \\" >> $DST/src/Makefile.am
		echo -n "	\$(top_builddir)/`basename $DST`/$i/lib$lib.la" >> $DST/src/Makefile.am
	fi
done
echo "" >> $DST/src/Makefile.am
echo "" >> $DST/src/Makefile.am


echo "# autogenerated Makefile.am" > $DST/Makefile.am
echo "# all changes will be lost when the next ufo version is imported" >> $DST/Makefile.am
echo "" >> $DST/Makefile.am
echo "SUBDIRS = src" >> $DST/Makefile.am

config=$DST/include/ufo/config/ufo_config_gnu.hpp
echo "Replacing ufo_config_gnu.hpp with our own version"
echo "#ifndef UFO_CONFIG_GNU_HPP" > $config
echo "#define UFO_CONFIG_GNU_HPP" >> $config
echo "#include <config.h>" >> $config
echo "" >> $config
echo "#ifdef UFO_USE_X11" >> $config
echo "#undef UFO_USE_X11" >> $config
echo "#endif" >> $config
echo "#ifdef UFO_USE_GLX" >> $config
echo "#undef UFO_USE_GLX" >> $config
echo "#endif" >> $config
echo "#ifdef UFO_USE_SDL" >> $config
echo "#undef UFO_USE_SDL" >> $config
echo "#endif" >> $config
echo "#ifdef UFO_USE_WGL" >> $config
echo "#undef UFO_USE_WGL" >> $config
echo "#endif" >> $config
echo "#define UFO_BUILDING_DLL" >> $config
echo "" >> $config
echo "// we use an empty DATADIR string here. note that you MUST set the data_dir property in the UToolkit before you can use it!" >> $config
echo "#define UFO_DATADIR \"\"" >> $config
echo "" >> $config
echo "#endif" >> $config
echo "" >> $config

configure=$DST/configure.in.in
echo "Generating configure.in.in"
echo "# autogenerated Makefile.am" > $configure
echo "# all changes will be lost when the next ufo version is imported" >> $configure
echo "" >> $configure
cat $SRC/configure.ac | while read i ; do
	if [ ! -z "$i" -a ! -z "`echo $i | sed "s/.*UFO_DATADIR.*//"`" ]; then
		if [ -z "`echo $i | sed "s/^UFO_[A-Z_]*VERSION=.*//"`" ]; then
			echo "$i" >> $configure
		elif [ -z "`echo $i | sed "s/^AC_SUBST(UFO_[A-Z]*VERSION)//"`" ]; then
			echo "$i" >> $configure
		elif [ -z "`echo $i | sed "s/^AC_CHECK_HEADERS(.*)//"`" ]; then
			echo "AC_LANG_SAVE" >> $configure
			echo "AC_LANG_CPLUSPLUS" >> $configure
			echo "$i" >> $configure
			echo "AC_LANG_RESTORE" >> $configure
		fi
	fi
done
echo "" >> $configure
echo "LIB_UFO=\"\\\$(top_builddir)/ufo/src/libufo.la\"" >> $configure
echo "UFO_INCLUDES=\"-I\\\$(top_srcdir)/ufo/include\"" >> $configure
echo "AC_SUBST(LIB_UFO)" >> $configure
echo "AC_SUBST(UFO_INCLUDES)" >> $configure
echo "" >> $configure



