Import('env')

data = """
	attack.png
	bomb.png
	follow.png
	harvest.png
	mine.png
	move.png
	repair.png
	stop.png
"""

destinationdir = env['KDEDATA'] + '/boson/themes/species/smackware1/pixmaps'

env.Install(destinationdir, env.make_list(data))
env.Alias('install', destinationdir)
