Import('env')

openal_sources = """
	bosonaudioal.cpp
	bosonsound.cpp
	bosonmusic.cpp
"""

lib = env.kobject('staticlib')
lib.target = 'libbosonsoundopenal'
lib.source = openal_sources
lib.includes = '../../bodebug'
lib.env = env
lib.execute()


