// This file was generated from ext_polygon_offset_decl_p.boglc
// Do not edit this file (all changes will be lost)!

#ifndef EXT_POLYGON_OFFSET_DECL_P_H
#define EXT_POLYGON_OFFSET_DECL_P_H

#ifndef BOGL_H
#error Never include this file directly! Include bogl.h instead!
#endif

#include "bogl/bogl_do_dlopen.h"




extern "C" {
	// typedefs
	typedef void (*_glPolygonOffsetEXT)(GLfloat factor, GLfloat bias);


	// Function pointers
	extern _glPolygonOffsetEXT bo_glPolygonOffsetEXT;
}


#define glPolygonOffsetEXT bo_glPolygonOffsetEXT

#endif // EXT_POLYGON_OFFSET_DECL_P_H
