Import('env')

bosonscript = env.kobject('staticlib')
bosonscript.target = 'libbosonscript'
bosonscript.includes = """
	../../../bodebug
	../../../bogl
"""
bosonscript.includes += env['PYTHON_INCLUDES']
bosonscript.source = """
	bosonscript.cpp
	pythonscript.cpp
	bosonscriptinterface.cpp
"""
bosonscript.execute()


