Import('env')

units = """
	barn1
	barrel-small
	broken_tree
	crate-cross
	crate-cross-double
	crate-plain
	crate-plain-double
	crate-wooden-1
	crate-wooden-1-double
	haystack1
	house-1
	rock1
	rubbishpile-1
	rubbishpile-1-big
	rubbishpile-1-small
	toilet
	tree1
	tree2
	tree3
	tree4
	tree4-big
	tree4-small
	tree5
	tree5-big
	tree5-small
	tree6
	tree6-big
	tree6-small
	oiltower
	mineralmine
	barn2
	containers1
	factory1
	factory2
	factory2-destroyed
	house2
	road1-curve
	road1-straight
	well1
	bush1
"""

destinationdir = env['KDEDATA'] + '/boson/themes/species/neutral/units'

for i in env.make_list(units):
	env.installDirectory(destinationdir, i)

