Import('env')

info = env.kobject('staticlib')
info.target = 'libbosoninfo'
info.includes = '../../bodebug ../../bogl'
info.source = """
	boinfo.cpp
	bocurrentinfo.cpp
	boinfoglcache.cpp
	boinfo_x11.cpp
	boinfodialog.cpp
	boglquerystates.cpp
"""
info.execute()



