Import('env')

boserver = env.kobject('program')
boserver.target = 'boserver'
boserver.includes = '../bodebug'
boserver.libs = """
	../kgame/libkgame.a
	../bodebug/libbodebug.a
	qt-mt
	kdecore
"""
boserver.source = """
	main.cpp
	server.cpp
	webinterface.cpp
	game.cpp
	player.cpp
"""
boserver.execute()

