#! /usr/bin/env python

Import('env')

events_dir = """
	events/uactionevent.cpp
	events/uevent.cpp
	events/ufocusevent.cpp
	events/uinputevent.cpp
	events/ukeyevent.cpp
	events/umouseevent.cpp
	events/umousewheelevent.cpp
	events/upropertychangeevent.cpp
	events/utimerevent.cpp
	events/uwidgetevent.cpp
"""

font_dir = """
	font/ufont.cpp
	font/utexturefont.cpp
"""

gl_dir = """
	gl/ugl_builtinfontrenderer.cpp
	gl/ugl_driver.cpp
	gl/ugl_font_data.cpp
	gl/ugl_graphics.cpp
	gl/ugl_image.cpp
	gl/ugl_texturefontrenderer.cpp
"""

image_dir = """
	image/pnm.cpp
	image/pnm.h
	image/tga.cpp
	image/tga.h
	image/uimage.cpp
	image/uimagefilter.cpp
	image/uimageicon.cpp
	image/uimageio.cpp
	image/uxbmicon.cpp
"""

layouts_dir = """
	layouts/uborderlayout.cpp
	layouts/uboxlayout.cpp
	layouts/uflowlayout.cpp
"""

text_dir = """
	text/ubasicdocument.cpp
	text/udocumentfactory.cpp
	text/utextlayout.cpp
"""

ui_dir = """
	ui/ubasicstyle.cpp
	ui/ucss.cpp
	ui/ustylehints.cpp
	ui/ustylemanager.cpp
"""

util_dir = """
	util/ucolor.cpp
	util/ufilearchive.cpp
	util/uinteger.cpp
	util/upalette.cpp
	util/uproperties.cpp
	util/ustring.cpp
"""

ux_dir = """
	ux/uxcontext.cpp
	ux/uxdisplay.cpp
	ux/uxframe.cpp
	ux/uxglxdriver.cpp
	ux/uxsdldriver.cpp
	ux/uxtoolkit.cpp
	ux/uxwgldriver.cpp
"""

widgets_dir = """
	widgets/uabstractslider.cpp
	widgets/ubutton.cpp
	widgets/ucheckbox.cpp
	widgets/ucheckboxmenuitem.cpp
	widgets/ucombobox.cpp
	widgets/ucompound.cpp
	widgets/udesktoppane.cpp
	widgets/udockwidget.cpp
	widgets/ugroupbox.cpp
	widgets/uinternalframe.cpp
	widgets/uitem.cpp
	widgets/ulabel.cpp
	widgets/ulayeredpane.cpp
	widgets/ulineedit.cpp
	widgets/ulistbox.cpp
	widgets/umenu.cpp
	widgets/umenubar.cpp
	widgets/umenuitem.cpp
	widgets/upopupmenu.cpp
	widgets/uprogressbar.cpp
	widgets/uradiobutton.cpp
	widgets/urootpane.cpp
	widgets/uscrollablewidget.cpp
	widgets/uscrollbar.cpp
	widgets/uscrollpane.cpp
	widgets/useparator.cpp
	widgets/uslider.cpp
	widgets/uspinbox.cpp
	widgets/utextedit.cpp
	widgets/utextwidget.cpp
	widgets/uviewport.cpp
	widgets/uwidget.cpp
"""

xml_dir = """
	xml/tinyxml.cpp
	xml/tinyxmlerror.cpp
	xml/tinyxmlparser.cpp
	xml/uxul.cpp
"""

ufo = env.kobject('staticlib')
ufo.target = 'libufo'
ufo.includes = '../../bogl ../include'
ufo.source = """
	uabstractcontext.cpp
	uabstractdisplay.cpp
	uabstracttoolkit.cpp
	ubuttongroup.cpp
	ucollectable.cpp
	ucontextgroup.cpp
	ufo_debug.cpp
	ufocusmanager.cpp
	ukeystroke.cpp
	umenumanager.cpp
	uobject.cpp
	uplugin.cpp
	upopupmanager.cpp
	urepaintmanager.cpp
	usharedlib.cpp
	uvalidator.cpp
	uvertexarray.cpp
	uvolatiledata.cpp
"""
ufo.source += events_dir
ufo.source += font_dir
ufo.source += gl_dir
ufo.source += image_dir
ufo.source += layouts_dir
ufo.source += text_dir
ufo.source += ui_dir
ufo.source += util_dir
ufo.source += ux_dir
ufo.source += widgets_dir
ufo.source += xml_dir
ufo.execute()

