

all: Makefile
	make all

Makefile: configure
	./configure --with-qt-dir=/opt/be/qt --with-kde-dir=/opt/be  --prefix=/opt/be

configure: Makefile.in
	autoconf

Makefile.in: Makefile.am
	aclocal
	autoheader
	automake
	perl am_edit
