#! /usr/bin/env python

VERSION='0.12pre'
APPNAME='boson'


bld.m_prune=['build', 'build-cmake']
bld.set_dirs('.', '_build_')
bld.set_default_env('main.cache.py')

from Common import cppobj
from Tools.KDE3 import kdeobj, kde_translations, kde_documentation
from Common import install_files, install_as

subdirs = ''
#if env['LIB_BOMEMORY']:
#	subdirs += 'bomemory'
subdirs += """
	math
	bobmfconverter
	bodebug
	bogl
	kgame
	ufo
	boson
	server
"""
#add_subdir(subdirs)

add_subdir('math')
add_subdir('bodebug')
add_subdir('bogl')
add_subdir('kgame')
add_subdir('ufo') # AB: FIXME: waf doesn't like this. waf is broken.
add_subdir('boson')


#Utils.g_debug = print

