#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

APPNAME='boson'
VERSION='0.12pre'

import os
import Configure

srcdir = '.'
blddir = '_build_'
cachedir = os.sep.join(['_build_', 'cache'])

prunedirs = ['build', 'build-cmake']


subdirs = ''
#if env['LIB_BOMEMORY']:
#	subdirs += 'bomemory'
subdirs += """
	math
	bodebug
	bogl
"""
"""
	bobmfconverter
	kgame
	ufo
	boson
	server
"""


def set_options(opt):
	opt.add_option('--prefix', type='string', help='installation prefix', dest='prefix')
	opt.add_option('--destdir', type='string', help='destination for install (when creation rpms or debs)', dest='destdir')


	"""
def setup_build(bld):
	pass
	bld.m_prune = ['build', 'build-cmake']
	bld.set_dirs('.', blddir)
	bld.set_default_env('main.cache.py')

	for dir in subdirs.split():
		print dir
		bld.add_subdir(dir)
	"""


def configure(conf):
	conf.checkTool(['g++', 'KDE3'])
	conf.checkHeader('dlfcn.h','HAVE_DLFCN_H')
	conf.addDefine('TEST_DEFINE', '345')
	conf.writeConfigHeader('config.h')

def build(bld):
	for dir in subdirs.split():
		bld.add_subdir(dir)

