Import('env')

mobile_units = """
	air_owl
	air_shark
	mob_bulldog
	mob_wolf
	mob_mineralharvester
	mob_oilharvester
	mob_gecko
	mob_frog
	mob_leo
"""
facilities = """
	fix_commandcenter
	fix_mineralrefinery
	fix_oilrefinery
	fix_powerplant
	fix_samsite
	fix_turret
	fix_factory
"""

units = mobile_units + facilities

destinationdir = env['KDEDATA'] + '/boson/themes/species/smackware1/units'

for i in env.make_list(units):
	env.installDirectory(destinationdir, i)

