

all: Makefile
	make all

re: re_pre all

re_pre:
	rm -f config.cache configure Makefile.in Makefile

Makefile: configure
	./configure --enable-debug --with-qt-dir=/opt/be/qt --with-kde-dir=/opt/be  --prefix=/opt/be

configure: Makefile.in
	autoconf

Makefile.in: Makefile.am
	aclocal
	autoheader
	automake
	perl am_edit
