Import('env')

source = """
	bosongameviewpluginfactory.cpp
	bosongameviewplugindefault.cpp
	boselectiondebugwidget.cpp
	editorrandommapwidget.cpp
	bodebugconfigswitches.cpp
"""

if not env['BOSON_USE_PLUGINS']:
	lib = env.kobject('staticlib')
	lib.target = 'libbosongameviewplugin_static'
	lib.includes = '../../../bodebug ../../../bogl'
	lib.source = source
	lib.env = env
	lib.execute()
else:
	plugin = env.boobject('boplugin')
	plugin.target = 'libbosongameviewplugin'
	plugin.includes = '../../../bodebug ../../../bogl'
	plugin.source = source
	plugin.env = env
	plugin.execute()

