Import('env')

source = """
	bosongameviewpluginfactory.cpp
	bosongameviewplugindefault.cpp
	boselectiondebugwidget.cpp
	editorrandommapwidget.cpp
"""

lib = env.kobject('staticlib')
lib.target = 'libplugin_static'
lib.includes = '../../../bodebug ../../../bogl'
lib.source = source
lib.env = env
lib.execute()


plugin = env.kobject('shlib')
plugin.target = 'libplugin'
plugin.includes = '../../../bodebug ../../../bogl'
#plugin.libs = './libplugin.a'
plugin.source = source
plugin.env = env
plugin.execute()

