#!/bin/bash

function delete_files()
{
 echo "Delete files:"
 echo " $1"
 rm $1
}

function delete_dir()
{
 echo "Delete dir:"
 echo " $1"
 rm -rf $1
}


if [ "x$KDEDIR" = "x" ]; then
	echo "Oops - \$KDEDIR is not set but this script needs it!"
	echo "Please enter the top level location of your kde installation now"
	echo "(e.g. /opt/kde3)"
	read KDEDIR
fi


echo "WARNING: This script tries to delete a boson installation completely from your system!"
echo "There might be bugs here which migh lead to files being deleted that don't belong to boson"
echo "Type yes if you want to execute anyeay"
read answer
if [ "x$answer" != "xyes" ]; then
	echo "Aborting"
	exit 1
fi

# this might be dangerous!
delete_files "$KDEDIR/bin/bo*"

delete_files "$KDEDIR/share/config/bodebug*"
delete_files "$KDEDIR/share/icons/*/*/apps/boson.png"
delete_files "$KDEDIR/share/applnk/Games/TacticStrategy/boson.desktop"
delete_files "$KDEDIR/share/applnk/Games/TacticStrategy/bounit.desktop"
delete_dir "$KDEDIR/share/doc/HTML/en/boson"
delete_dir "$KDEDIR/share/apps/boson"
delete_dir "$KDEDIR/share/apps/borender"

# now from $KDEHOME
if [ "x$KDEHOME" = "x" ]; then
	# TODO: check $KDEDIRS!
	echo "\$KDEHOME is not set - using ~/.kde in 4 seconds."
	echo "press CTRL+C to abort!"
	sleep 4
	KDEHOME="~/.kde"
fi

# this might be dangerous
delete_files "$KDEHOME/share/config/bo*rc"

delete_dir "$KDEHOME/share/apps/boson"
