Import('env')

groundrenderer_sources = """
	bogroundrendererfactory.cpp
	bodefaultgroundrenderer.cpp
	bofastgroundrenderer.cpp
	boveryfastgroundrenderer.cpp
	boquickgroundrenderer.cpp
	bogroundrendererbase.cpp
	bocolormaprenderer.cpp
"""

if not env['BOSON_USE_PLUGINS']:
	lib = env.kobject('staticlib')
	lib.target = 'libbogroundrendererplugin_static'
	lib.includes = '../../bodebug ../../bogl'
	lib.source = groundrenderer_sources
	lib.execute()
else:
	plugin = env.boobject('boplugin')
	plugin.target = 'libbogroundrendererplugin'
	plugin.includes = '../../bodebug ../../bogl'
	plugin.source = groundrenderer_sources
	plugin.execute()

