#! /usr/bin/env python

from Object import createObj

obj = createObj('kde', 'staticlib')
obj.source = """
	bogl.cpp
	bogl_resolve.cpp
"""
obj.target = 'bogl'
obj.includes = '. ../bodebug'
obj.uselib = 'QT'

