#! /usr/bin/env python

kmessage_sources = """
	kmessageio.cpp
	kmessageserver.cpp
	kmessageclient.cpp
"""

kgame_sources = """
	kgame.cpp
	kplayer.cpp
	kgamenetwork.cpp
	kgameproperty.cpp
	kgamemessage.cpp
	kgameio.cpp
	kgameprocess.cpp
	kgamechat.cpp
	kgamepropertyhandler.cpp
	kgameerror.cpp
	kgamesequence.cpp
"""

dialogs_sources = """
	kgamedebugdialog.cpp
"""

libkdegames_sources = """
	kchatbase.cpp
	kgameprogress.cpp
	kstdgameaction.cpp
"""

obj = kdeobj('staticlib')

obj.source = kmessage_sources + kgame_sources + dialogs_sources + libkdegames_sources

obj.uselib = 'QT KDECORE'
obj.target = 'kgame'
obj.includes = '. ../bodebug'

