Import('env')

data = """
	minimap-logo.png
	minimap-zoom-in.png
	minimap-zoom-out.png
	minimap-zoom-default.png
	circle-constant.png
"""

destinationdir = env['KDEDATA'] + '/boson/themes/ui/standard'

env.Install(destinationdir, env.make_list(data))
env.Alias('install', destinationdir)

