Import('env')

bomemory = env.kobject('staticlib')
bomemory.target = 'libbomemory'
bomemory.includes = '../bodebug'
bomemory.source = """
	new.cpp
	memnode.cpp
	memorymanager.cpp
	bomemorydialog.cpp
	malloc.cpp
"""
bomemory.execute()

