/* config.h. Generated by cmake from config.h.cmake */

/********** libufo *************/
#cmakedefine   HAVE_SSTREAM 1
#cmakedefine   HAVE_STRSTREAM 1
#cmakedefine   HAVE_STDINT_H 1
#cmakedefine   HAVE_EXECINFO_H 1
#cmakedefine   HAVE_PWD_H 1
#cmakedefine   HAVE_DLFCN_H 1

