Import('env')

env.subdirs(['bouic', 'designer'])

ufoext_sources = """
	ufoext/boufofontrenderer.cpp
	ufoext/ubosonstyle.cpp
	ufoext/ubolabel.cpp
	ufoext/ubolabelui.cpp
	ufoext/uboprogress.cpp
	ufoext/ubogridlayout.cpp
	ufoext/ubodrawableicon.cpp
	ufoext/uboboxlayout.cpp
"""

bosonfont_sources = """
	bosonfont/fnt.cpp
	bosonfont/fntTXF.cpp
	bosonfont/bosonglfont.cpp
"""

libboufo = env.kobject('staticlib')
libboufo.target = 'libboufo'
libboufo.includes = '../../bodebug ../../bogl ../../ufo/include'

# TODO: $(UFO_CFLAGS)
#libboufo.cxxflags = ...

libboufo.source = """
	boufofontinfo.cpp
	boufodrawable.cpp
	boufoimage.cpp
	boufowidget.cpp
	boufolabel.cpp
	boufolineedit.cpp
	boufotextedit.cpp
	boufopushbutton.cpp
	boufolistbox.cpp
	boufocombobox.cpp
	boufocheckbox.cpp
	bouforadiobutton.cpp
	boufomatrix.cpp
	boufoslider.cpp
	boufoprogress.cpp
	boufonuminput.cpp
	boufowidgetstack.cpp
	boufotabwidget.cpp
	boufolayeredpane.cpp
	boufowidgetstack.cpp
	boufogroupbox.cpp
	boufocustomwidget.cpp
	boufointernalframe.cpp
	boufoinputdialog.cpp
	boufomanager.cpp
	boufofactory.cpp
	boufoaction.cpp
	boufodebugwidget.cpp
	boufostandalonefont.cpp
	boufoprofiling.cpp
"""
libboufo.source += ufoext_sources
libboufo.source += bosonfont_sources
libboufo.execute()


