Import('env')

scripts = """
	ai.py
	ai_produce.py
	ai_attack.py
	bomath.py
	camera.py
	conditions1.py
	dayandnight.py
	unit.py
	utils.py
	wind.py
"""

scriptsdir = env['KDEDATA'] + '/boson/themes/scripts'

env.Install(scriptsdir, env.make_list(scripts))
env.Alias('install', scriptsdir)

