Import('env')

data = """
	order_move_0.ogg
	order_move_1.ogg
	order_attack_0.ogg
	order_select_0.ogg
	order_select_warfactory_0.ogg
	order_select_cmdbunker_0.ogg
	report_destroyed_0.ogg
	report_produced_0.ogg
	report_underattack_0.ogg
	report_minimap_activated.ogg
	report_minimap_deactivated.ogg
	radar_pulse.ogg
	shoot_1.ogg
	shoot_2.ogg
	shoot_3.ogg
	shoot_4.ogg
	shoot_5.ogg
	engine1_start.ogg
	engine1_stop.ogg
	engine1_idle.ogg
	explosion_1.ogg
	machine_gun_2.ogg
"""

destinationdir = env['KDEDATA'] + '/boson/themes/species/smackware1/sounds'

env.Install(destinationdir, env.make_list(data))
env.Alias('install', destinationdir)
