Import('env')

mobile_units = """
	mob_ferry
	mob_grizzly
	mob_koyote
	mob_leopard
	mob_mineralharvester
	mob_oilharvester
	mob_panther
	mob_piranha
	mob_puma
	mob_ship
	mob_tiger
	mob_tornado
	mob_transall
	mob_warthog
	mob_wolf
"""
facilities = """
	fix_airport
	fix_airturret
	fix_barracks
	fix_commandbunker
	fix_comsat
	fix_airradar
	fix_groundradar
	fix_helipad
	fix_mineralrefinery
	fix_oilrefinery
	fix_powerplant
	fix_prison
	fix_repairpad
	fix_samsite
	fix_techcenter
	fix_turret
	fix_weaponsfactory
	fix_turret_base_mount_01
	fix_turret_base_mount_02
	fix_turret_base_mount_03
"""

units = mobile_units + facilities

destinationdir = env['KDEDATA'] + '/boson/themes/species/human/units'

for i in env.make_list(units):
	env.installDirectory(destinationdir, i)

