Import('env')

libgfx_sources = """
	libgfx/geom3d.cxx
	libgfx/geom4d.cxx
	libgfx/gltools.cxx
	libgfx/gui.cxx
	libgfx/mat2.cxx
	libgfx/mat3.cxx
	libgfx/mat4.cxx
	libgfx/quat.cxx
	libgfx/raster-jpeg.cxx
	libgfx/raster-png.cxx
	libgfx/raster-pnm.cxx
	libgfx/script.cxx
	libgfx/symmat3.cxx
	libgfx/symmat4.cxx
	libgfx/time.cxx
"""
#	libgfx/trackball.cxx
#	libgfx/raster.cxx
#	libgfx/arcball.cxx
#	libgfx/baseball.cxx
#	libgfx/raster-tiff.cxx

libmixkit_sources = """
	mixkit/MxAsp.cxx
	mixkit/MxBlockModel.cxx
	mixkit/MxCmdParser.cxx
	mixkit/MxDualModel.cxx
	mixkit/MxDualSlim.cxx
	mixkit/MxEdgeFilter.cxx
	mixkit/MxFaceTree-2.cxx
	mixkit/MxFaceTree.cxx
	mixkit/MxFeatureFilter.cxx
	mixkit/MxFitFrame-2.cxx
	mixkit/MxFitFrame.cxx
	mixkit/MxFrame.cxx
	mixkit/MxGeom2D.cxx
	mixkit/MxGeom3D.cxx
	mixkit/MxHeap.cxx
	mixkit/MxMat3-jacobi.cxx
	mixkit/MxMat4-jacobi.cxx
	mixkit/MxMatrix.cxx
	mixkit/MxPropSlim.cxx
	mixkit/MxQMetric.cxx
	mixkit/MxQMetric3.cxx
	mixkit/MxQSlim.cxx
	mixkit/MxSMF.cxx
	mixkit/MxStdModel.cxx
	mixkit/MxStdSlim.cxx
	mixkit/MxTriProject.cxx
	mixkit/mixmops.cxx
	mixkit/mixmsg.cxx
"""
#	mixkit/MxCamera.cxx
#	mixkit/MxFitFrame-vis.cxx
#	mixkit/MxGLDebug.cxx
#	mixkit/MxGLUtils.cxx
#	mixkit/MxQVis3.cxx
#	mixkit/MxStdRender.cxx

#INCLUDES = -I$(top_srcdir)/bobmfconverter -I$(top_srcdir)/bobmfconverter/mixkit -I$(top_srcdir)/bobmfconverter/libgfx $(all_includes)
#INCLUDES = $(all_includes) -I$(top_srcdir)/bobmfconverter/libgfx
#INCLUDES = $(all_includes) -I$(top_srcdir)/bobmfconverter/libgfx -I$(top_srcdir)/bobmfconverter/mixkit

bobmfconverter = env.kobject('program')
bobmfconverter.target = 'bobmfconverter'
bobmfconverter.libs = '3ds qt-mt kdecore'
bobmfconverter.includes = """
	libgfx
	mixkit
"""
bobmfconverter.source = """
	main.cpp
	bo3dtools.cpp
	frame.cpp
	loader.cpp
	lod.cpp
	material.cpp
	mesh.cpp
	model.cpp
	processor.cpp
	saver.cpp
	texture.cpp
"""
bobmfconverter.source += """
	processors/frameoptimizer.cpp
	processors/lodcreator.cpp
	processors/materialoptimizer.cpp
	processors/meshoptimizer.cpp
	processors/textureoptimizer.cpp
	processors/transformer.cpp
	processors/unuseddataremover.cpp
	processors/vertexoptimizer.cpp
"""
bobmfconverter.source += """
	loaders/loader-3ds.cpp
	loaders/loader-ac.cpp
	loaders/loader-md2.cpp
"""
bobmfconverter.source += libgfx_sources
bobmfconverter.source += libmixkit_sources
bobmfconverter.execute()

