// This file was generated from specs/extensions/ext_blend_color_decl_p.boglc
// Do not edit this file (all changes will be lost)!
#ifndef EXT_BLEND_COLOR_DECL_P_H
#define EXT_BLEND_COLOR_DECL_P_H

#ifndef BOGL_H
#error Never include this file directly! Include bogl.h instead!
#endif

#include "bogl/bogl_do_dlopen.h"




#define GL_CONSTANT_COLOR_EXT                 0x8001
#define GL_ONE_MINUS_CONSTANT_COLOR_EXT       0x8002
#define GL_CONSTANT_ALPHA_EXT                 0x8003
#define GL_ONE_MINUS_CONSTANT_ALPHA_EXT       0x8004
#define GL_BLEND_COLOR_EXT                    0x8005



extern "C" {
	// typedefs
	typedef void (*_glBlendColorEXT)(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);


	// Function pointers
	extern _glBlendColorEXT bo_glBlendColorEXT;
}


#if BOGL_DO_DLOPEN
#define glBlendColorEXT bo_glBlendColorEXT
#endif // BOGL_DO_DLOPEN

#endif // EXT_BLEND_COLOR_DECL_P_H
