Import('env')

data = """
	testtech.png
	armor_plus2.png
	grizzlymissiles.png
	samsitemissiles.png
	turretupgrade.png
	attack.png
	bomb.png
	follow.png
	harvest.png
	mine.png
	move.png
	repair.png
	stop.png
"""

destinationdir = env['KDEDATA'] + '/boson/themes/species/human/pixmaps'

env.Install(destinationdir, env.make_list(data))
env.Alias('install', destinationdir)
