Import('env')

meshrenderer_sources = """
	bomeshrendererfactory.cpp
	bomeshrendererimmediate.cpp
	bomeshrenderersemiimmediate.cpp
	bomeshrenderervertexarray.cpp
	bomeshrenderervbo.cpp
"""

if env['BOSON_DO_STATIC']:
	lib = env.kobject('staticlib')
	lib.target = 'libbomeshrendererplugin_static'
	lib.includes = '../../bodebug ../../bogl'
	lib.source = meshrenderer_sources
	lib.execute()
else:
	plugin = env.boobject('boplugin')
	plugin.target = 'libbomeshrendererplugin'
	plugin.includes = '../../bodebug ../../bogl'
	plugin.source = meshrenderer_sources
	plugin.execute()

