#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

conf = Configure.Configure()
conf.checkTool(['g++', 'KDE3'])

# hand-written defines - comment
conf.addDefine('HAVE_SSTREAM', 1)
conf.addDefine('HAVE_STRSTREAM', 1)
conf.addDefine('HAVE_STDINT_H', 1)
conf.addDefine('HAVE_EXECINFO_H', 1)
conf.addDefine('HAVE_PWD_H', 1)
conf.addDefine('HAVE_DLFCN_H', 1)

# TODO
conf.addDefine('BOSON_PREFIX', '""')

conf.checkHeader('sstream','HAVE_SSTREAM')
conf.checkHeader('strstream','HAVE_STRSTREAM')
conf.checkHeader('stdint.h','HAVE_STDINT_H')
conf.checkHeader('execinfo.h','HAVE_EXECINFO_H')
conf.checkHeader('pwd.h','HAVE_PWD_H')
conf.checkHeader('dlfcn.h','HAVE_DLFCN_H')

conf.store('main.cache.py')

try:
	os.mkdir('_build_')
except OSError:
	pass
conf.writeConfigHeader('_build_/config.h')

