Import('env')

bodebugdialog = env.kobject('program')
bodebugdialog.target = 'bodebugdialog'
bodebugdialog.libs = """
	../libbodebug.a
	kdeui
	qt-mt
"""
if env['LIB_BOMEMORY']:
	bodebugdialog.libs += ' ' + env['LIB_BOMEMORY']
bodebugdialog.source = """
	boabstractdebugdialog.cpp
	bodebugdialog.cpp
	bolistdebugdialog.cpp
	main.cpp
"""
bodebugdialog.execute()

