#! /usr/bin/env python

from Object import createObj

#obj = kdeobj('staticlib')
obj = createObj('kde', 'staticlib')
obj.target = 'bomath'
obj.source = """
	bomath.cpp
	bofixed.cpp
	bo3dtoolsbase.cpp
	bovector.cpp
	borect.cpp
	borect.cpp
	bomatrix.cpp
	boquaternion.cpp
	boplane.cpp
	bofrustum.cpp
	boglmatrices.cpp
"""
obj.uselib = 'QT'
obj.includes = '..'

