// This file was generated from specs/extensions/ext_texture3d_decl_p.boglc
// Do not edit this file (all changes will be lost)!
#ifndef EXT_TEXTURE3D_DECL_P_H
#define EXT_TEXTURE3D_DECL_P_H

#ifndef BOGL_H
#error Never include this file directly! Include bogl.h instead!
#endif

#include "bogl/bogl_do_dlopen.h"





extern "C" {
	// typedefs
	typedef void (*_glTexImage3DEXT)(GLenum target, GLint level, GLenum internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid* pixels);
	typedef void (*_glTexSubImage3DEXT)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid* pixels);
	typedef void (*_glCopyTexSubImage3DEXT)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);


	// Function pointers
	extern _glTexImage3DEXT bo_glTexImage3DEXT;
	extern _glTexSubImage3DEXT bo_glTexSubImage3DEXT;
	extern _glCopyTexSubImage3DEXT bo_glCopyTexSubImage3DEXT;
}


#if BOGL_DO_DLOPEN
#define glTexImage3DEXT bo_glTexImage3DEXT
#define glTexSubImage3DEXT bo_glTexSubImage3DEXT
#define glCopyTexSubImage3DEXT bo_glCopyTexSubImage3DEXT
#endif // BOGL_DO_DLOPEN

#endif // EXT_TEXTURE3D_DECL_P_H
