#! /usr/bin/env python

Import('env')

env.subdirs('bodebugdialog')

stlib = env.kobject('staticlib')
stlib.target = 'libbodebug'
stlib.source = """
bodebug.cpp
bodebugdcopiface.cpp
bodebuglog.cpp
bodebugdcopiface.skel
"""
stlib.execute()

