#! /usr/bin/env python

obj = kdeobj('staticlib')
obj.source = """
	bodebug.cpp
	bodebugdcopiface.cpp
	bodebuglog.cpp
	bodebugdcopiface.skel
"""
obj.target = 'bodebug'
obj.uselib = 'QT KDECORE'
obj.includes = '. ../bodebug'

add_subdir('bodebugdialog')

