#! /usr/bin/env python

from Object import createObj

obj = createObj('kde', 'staticlib')
obj.source = """
	bodebug.cpp
	bodebugdcopiface.cpp
	bodebuglog.cpp
	bodebugdcopiface.skel
"""
obj.target = 'bodebug'
obj.uselib = 'QT KDECORE'
obj.includes = '. ../bodebug'

add_subdir('bodebugdialog')

